### ISSUE TITLE
Can you provide the complete code needed to run the experiment?

### ISSUE THREAD

**Issue by Yurri-hub** [82magnolia/cpo#1]
Hi,

Thanks for your great work! Can you provide the complete code needed to run the experiment?

**Comment by 82magnolia** [comment]
Hello,

Sorry for the late reply. Due to several ongoing projects and deadlines, I plan to release an extended version of the codebase around March. Stay tuned for updates! Meanwhile, I suggest checking out the publicly available implementation of [PICCOLO](https://github.com/82magnolia/piccolo), which is the predecessor version of CPO:)
